---
# - name: Run common role
#   hosts: all
#   become: true
#   vars_files:
#     - ../environments/{{ environment_name }}/vars/proj_bilolok_vars.yml
#   roles:
#     - ../roles/common
#
# - name: Run Docker role
#   hosts: all
#   become: true
#   roles:
#     - ../roles/docker
#   vars_files:
#     - ../environments/{{ environment_name }}/vars/proj_bilolok_vars.yml
#   vars:
#     my_docker_users:
#       - "{{ username }}"
#     include_optional_compose_systemd_setup: false
#
# - name: Run nginx role
#   hosts: all
#   become: true
#   roles:
#     - ../roles/nginx
#   vars_files:
#     - ../environments/{{ environment_name }}/vars/proj_bilolok_vars.yml
#
# - name: Run certbot role
#   hosts: all
#   become: true
#   roles:
#     - ../roles/certbot
#   vars_files:
#     - ../environments/{{ environment_name }}/vars/proj_bilolok_vars.yml
#     - ../environments/{{ environment_name }}/vars/proj_bilolok_vault.yml
#
# - name: Prepare frontend environment on localhost
#   hosts: localhost
#   vars_files:
#     - ../environments/{{ environment_name }}/vars/proj_bilolok_vars.yml
#     - ../environments/{{ environment_name }}/vars/proj_bilolok_vault.yml
#   vars:
#     local_frontend_directory: "{{ local_project_directory }}/frontend"
#   tasks:
#     - name: Include frontend tasks from role
#       include_tasks: "../roles/proj_bilolok/tasks/task-build-frontend-locally.yml"

- name: Run application role
  hosts: all
  become: true
  vars_files:
    - ../environments/{{ environment_name }}/vars/proj_bilolok_vars.yml
    - ../environments/{{ environment_name }}/vars/proj_bilolok_vault.yml
  vars:
    app_root: "/opt/{{ app_name }}"
    app_directory: "/opt/{{ app_name }}/app"
    data_directory: "/opt/{{ app_name }}/data"
    www_directory: "/opt/{{ app_name }}/www"
    local_frontend_directory: "{{ local_project_directory }}/frontend"
    html_files:
      - privacy-policy
      - terms-and-conditions
      - delete-user-account
      - delete-user-data
  roles:
    - ../roles/proj_bilolok
