#! /bin/bash

cat <<EOF
# generated by OpenTofu

all:
  vars:
    username: $USERNAME
    ansible_ssh_user: $USERNAME
    ansible_private_key_file: $SSH_PRIVKEY
  children:
    webservers:
      hosts:
        www:
          ansible_host: $HOST_IP
EOF
