---
- name: Include geerlingguy.nginx role
  include_role:
    name: geerlingguy.nginx
  vars:
    nginx_listen_ipv6: true
    nginx_vhosts: []
    nginx_remove_default_vhost: true
    nginx_ppa_use: false
    nginx_ppa_version: stable
    nginx_service_state: started
    nginx_service_enabled: true
